version: "3.9"
services:
  rails:
    image: timbru31/ruby-node:3.0-16
    user: "${UID:-1000}"
    tty: true
    stdin_open: true
    working_dir: /myapp
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./backend:/myapp
      - bundler_cache:/usr/local/bundle
      - ./docker/rails/home:/home/developer
    environment:
      - HOME=/home/developer
  frontend:
    image: node:18
    user: "${UID:-1000}"
    tty: true
    stdin_open: true
    working_dir: /myapp
    environment:
      - PORT=4200
    ports:
      - 4200:4200
    command: npm start
    volumes:
      - ./frontend:/myapp
      - npm_cache:/myapp/node_modules
volumes:
  bundler_cache:
  npm_cache:
