require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tours", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Tour. As you add validations to Tour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ToursController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tour.create! valid_attributes
      get tours_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end

    it "filters tours by sport kind" do
      tours_url = tours_url(filter: {sport_kind: 'alpine_summer'})
      get tours_url
      expect(response).to be_successful
      expect(json_data.size).to eq(1)
      tour_label = json_data.first['attributes']['label']
      expect(tour_label).to eq('Dom 4545m')
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tour = Tour.create! valid_attributes
      get tour_url(tour), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tour" do
        expect {
          post tours_url,
               params: { tour: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Tour, :count).by(1)
      end

      it "renders a JSON response with the new tour" do
        post tours_url,
             params: { tour: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tour" do
        expect {
          post tours_url,
               params: { tour: invalid_attributes }, as: :json
        }.to change(Tour, :count).by(0)
      end

      it "renders a JSON response with errors for the new tour" do
        post tours_url,
             params: { tour: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tour" do
        tour = Tour.create! valid_attributes
        patch tour_url(tour),
              params: { tour: new_attributes }, headers: valid_headers, as: :json
        tour.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the tour" do
        tour = Tour.create! valid_attributes
        patch tour_url(tour),
              params: { tour: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the tour" do
        tour = Tour.create! valid_attributes
        patch tour_url(tour),
              params: { tour: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tour" do
      tour = Tour.create! valid_attributes
      expect {
        delete tour_url(tour), headers: valid_headers, as: :json
      }.to change(Tour, :count).by(-1)
    end
  end
end
